[package]
name = "binpkg-cli"
version = "0.1.1"
edition = "2021"

[dependencies]
libspkg = { version = "0.1.6", features = ["binpkg"]}
subprocess = "0.2.9"
karen = "0.1.2"
serde_yaml = "0.9.34"
serde = { version = "1.0.209", features = ["derive"] }